### ISSUE TITLE
Fix /locations page

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1072]
```
[Thu May 31 09:35:54.785552 2018] [php7:notice] [pid 8934] [client 176.38.13.39:33964] Error: Class 'CommerceGuys\\Addressing\\LocaleHelper' not found in /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/modules/contrib/address/src/Plugin/Field/FieldFormatter/AddressPlainFormatter.php on line 202 #0 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/modules/contrib/address/src/Plugin/Field/FieldFormatter/AddressPlainFormatter.php(131): Drupal\\address\\Plugin\\Field\\FieldFormatter\\AddressPlainFormatter->getValues(Object(Drupal\\address\\Plugin\\Field\\FieldType\\AddressItem), Object(CommerceGuys\\Addressing\\AddressFormat\\AddressFormat))\n#1 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/modules/contrib/address/src/Plugin/Field/FieldFormatter/AddressPlainFormatter.php(110): Drupal\\address\\Plugin\\Field\\FieldFormatter\\AddressPlainFormatter->viewElement(Object(Drupal\\address\\Plugin\\Field\\FieldType\\AddressItem), 'en')\n#2 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\\address\\Plugin\\Field\\FieldFormatter\\AddressPlainFormatter->viewElements(Object(Drupal\\Core\\Field\\FieldItemList), 'en')\n#3 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(259): Drupal\\Core\\Field\\FormatterBase->view(Object(Drupal\\Core\\Field\\FieldItemList), 'en')\n#4 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(320): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->buildMultiple(Array)\n#5 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/modules/node/src/NodeViewBuilder.php(24): Drupal\\Core\\Entity\\EntityViewBuilder->buildComponents(Array, Array, Array, 'teaser')\n#6 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(263): Drupal\\node\\NodeViewBuilder->buildComponents(Array, Array, Array, 'teaser')\n#7 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(220): Drupal\\Core\\Entity\\EntityViewBuilder->buildMultiple(Array)\n#8 [internal function]: Drupal\\Core\\Entity\\EntityViewBuilder->build(Array)\n#9 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array)\n#10 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, true)\n#11 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(139): Drupal\\Core\\Render\\Renderer->render(Array, true)\n#12 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\Render\\Renderer->Drupal\\Core\\Render\\{closure}()\n#13 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(140): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#14 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/profiles/contrib/openy/modules/custom/openy_data_wrapper/src/DataWrapper.php(158): Drupal\\Core\\Render\\Renderer->renderRoot(Array)\n#15 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/profiles/contrib/openy/modules/custom/openy_data_wrapper/src/DataWrapper.php(101): Drupal\\openy_data_wrapper\\DataWrapper->getPins('branch', Object(Drupal\\Core\\StringTranslation\\TranslatableMarkup), 'blue')\n#16 [internal function]: Drupal\\openy_data_wrapper\\DataWrapper->getLocationPins()\n#17 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/profiles/contrib/openy/modules/custom/openy_socrates/src/OpenySocratesFacade.php(70): call_user_func_array(Array, Array)\n#18 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/profiles/contrib/openy/modules/custom/location_finder/src/Plugin/Block/LocationFinderFilters.php(56): Drupal\\openy_socrates\\OpenySocratesFacade->__call('getLocationPins', Array)\n#19 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/modules/contrib/plugin/src/Plugin/Field/FieldFormatter/BuiltBlock.php(30): Drupal\\location_finder\\Plugin\\Block\\LocationFinderFilters->build()\n#20 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\\plugin\\Plugin\\Field\\FieldFormatter\\BuiltBlock->viewElements(Object(Drupal\\plugin\\Plugin\\Field\\FieldType\\PluginCollectionItemList), 'en')\n#21 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(259): Drupal\\Core\\Field\\FormatterBase->view(Object(Drupal\\plugin\\Plugin\\Field\\FieldType\\PluginCollectionItemList), 'en')\n#22 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(320): Drupal\\Core\\Entity\\Entity\\EntityViewDisplay->buildMultiple(Array)\n#23 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(263): Drupal\\Core\\Entity\\EntityViewBuilder->buildComponents(Array, Array, Array, 'default')\n#24 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/modules/contrib/paragraphs/src/ParagraphViewBuilder.php(18): Drupal\\Core\\Entity\\EntityViewBuilder->buildMultiple(Array)\n#25 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(220): Drupal\\paragraphs\\ParagraphViewBuilder->buildMultiple(Array)\n#26 [internal function]: Drupal\\Core\\Entity\\EntityViewBuilder->build(Array)\n#27 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array)\n#28 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#29 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\\Core\\Render\\Renderer->render(Array)\n#30 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/sites/default/files/php/twig/5b0fb3fdd254c_field.html.twig_qiOJlIoFhclnOgknuBpYPc2Ly/RwxL7vzZjOzaD5Ava-5xphjRhk-OSk23UmkhmIfPUWQ.php(65): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#31 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_d0064aa91931fadf462f5f16952350c518abd500724121ed71abe08fdadaeb51->doDisplay(Array, Array)\n#32 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#33 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#34 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)\n#35 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/contri...', Array)\n#36 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('field', Array)\n#37 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#38 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\\Core\\Render\\Renderer->render(Array)\n#39 /var/lib/jenkins/jobs/SANDBOX_INSTALLATION/workspace/build/docroot/sites/default/files

```
When visiting /locations page on sandbox

**Comment by podarok** [comment]
All good. We need to make a release
