### ISSUE TITLE
ActivityFinder 2.0 fails on builds

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1669]
See
https://github.com/ymcatwincities/openy/pull/1668

```
Notice: Trying to get property of non-object in Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->processResults() (line 305 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php) #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Trying to get p...', '/var/lib/jenkin...', 305, Array) #1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php(305): _drupal_error_handler(8, 'Trying to get p...', '/var/lib/jenkin...', 305, Array) #2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php(136): Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->processResults(Object(Drupal\search_api\Query\ResultSet), '4') #3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/Controller/ActivityFinderController.php(100): Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->runProgramSearch(Array, '4') #4 [internal function]: Drupal\openy_activity_finder\Controller\ActivityFinderController->getData(Object(Symfony\Component\HttpFoundation\Request)) #5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #9 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #10 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #21 {main}.








Notice: Undefined index: ! in Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->getFacets() (line 393 of /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php) #0 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Undefined index...', '/var/lib/jenkin...', 393, Array) #1 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php(393): _drupal_error_handler(8, 'Undefined index...', '/var/lib/jenkin...', 393, Array) #2 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php(127): Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->getFacets(Object(Drupal\search_api\Query\ResultSet)) #3 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/custom/openy_activity_finder/src/Controller/ActivityFinderController.php(100): Drupal\openy_activity_finder\OpenyActivityFinderSolrBackend->runProgramSearch(Array, '4') #4 [internal function]: Drupal\openy_activity_finder\Controller\ActivityFinderController->getData(Object(Symfony\Component\HttpFoundation\Request)) #5 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #6 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #7 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #8 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #9 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #10 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-profile/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build1678/openy-project/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #21 {main}.
```

**Comment by podarok** [comment]
@paige-kiecker this one is critical
We'll work on reproducing on YGTC in next couple days with @danylevskyi 
I'll keep updated if this is issue for CI builds or common for OpenY

**Comment by podarok** [comment]
cc @anpolimus

**Comment by podarok** [comment]
https://github.com/ymcatwincities/openy/pull/1670

**Comment by podarok** [comment]
Fixed
