### ISSUE TITLE
Undefined index: #group_name in openy_node_landing_field_group_form_process_alter

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2006]
While testing Open Y I noticed the following notice. The notice should be fixed. 

`Notice: Undefined index: #group_name in openy_node_landing_field_group_form_process_alter() (line 12 of /var/www/openy/modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module)
#0 /var/www/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/openy/...', 12, Array)
#1 /var/www/openy/modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module(12): _drupal_error_handler(8, 'Undefined index...', '/var/www/openy/...', 12, Array)
#2 /var/www/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(539): openy_node_landing_field_group_form_process_alter(Array, Object(stdClass), Array)
#3 /var/www/docroot/modules/contrib/field_group/field_group.module(397): Drupal\Core\Extension\ModuleHandler->alter('field_group_for...', Array, Object(stdClass), Array)
#4 [internal function]: field_group_form_process(Array, Object(Drupal\Core\Form\FormState), Array)
#5 /var/www/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(999): call_user_func_array('field_group_for...', Array)
`

**Comment by ddrozdik** [comment]
Closing this one as a duplicated issue https://github.com/ymcatwincities/openy/issues/2005
