### ISSUE TITLE
Call to a member function getDefinition() on nul

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2132]
Edit `program-search` or any branch from demo

```
Error: Call to a member function getDefinition() on null in Drupal\openy_er\Plugin\EntityReferenceSelection\NodeSelectionNoDependency->buildEntityQuery() (line 119 of /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php)
#0 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/Plugin/EntityReferenceSelection/DefaultSelection.php(362): Drupal\openy_er\Plugin\EntityReferenceSelection\NodeSelectionNoDependency->buildEntityQuery()
#1 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php(133): Drupal\Core\Entity\Plugin\EntityReferenceSelection\DefaultSelection->validateReferenceableEntities()
#2 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(196): Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate()
#3 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(148): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints()
#4 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(158): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode()
#5 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(100): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode()
#6 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveValidator.php(90): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate()
#7 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/TypedData/TypedData.php(132): Drupal\Core\TypedData\Validation\RecursiveValidator->validate()
#8 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(489): Drupal\Core\TypedData\TypedData->validate()
#9 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(282): Drupal\Core\Entity\ContentEntityBase->validate()
#10 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(342): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->formElement()
#11 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(844): Drupal\Core\Field\WidgetBase->formSingleElement()
#12 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Field/WidgetBase.php(111): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->formMultipleElements()
#13 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php(955): Drupal\Core\Field\WidgetBase->form()
#14 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(178): Drupal\paragraphs\Plugin\Field\FieldWidget\InlineParagraphsWidget->form()
#15 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(121): Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm()
#16 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/node/src/NodeForm.php(127): Drupal\Core\Entity\ContentEntityForm->form()
#17 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Entity/EntityForm.php(106): Drupal\node\NodeForm->form()
#18 [internal function]: Drupal\Core\Entity\EntityForm->buildForm()
#19 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(532): call_user_func_array()
#20 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(278): Drupal\Core\Form\FormBuilder->retrieveForm()
#21 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#22 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#23 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#24 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#25 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#26 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#27 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#28 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#29 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#30 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#31 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#32 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#33 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle()
#34 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle()
#35 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#36 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#37 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle()
#38 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/index.php(19): Drupal\Core\DrupalKernel->handle()
#39 {main}
.
```

**Comment by podarok** [comment]
Try 1 https://github.com/ymcatwincities/openy/commit/ec4d35d2e7c9abdab293cb31d23ea7e95971e969

**Comment by podarok** [comment]
fixed
