### ISSUE TITLE
TypeError: Argument 1 passed to Drupal\Core\Cache\CacheableMetadata::applyTo() must be of the type array, null given,

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2138]
Adding Social List paragraph to Landing Page
```
TypeError: Argument 1 passed to Drupal\Core\Cache\CacheableMetadata::applyTo() must be of the type array, null given, called in /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Plugin/PluginSelector/AdvancedPluginSelectorBase.php on line 76 in Drupal\Core\Cache\CacheableMetadata->applyTo() (line 135 of /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Cache/CacheableMetadata.php)
#0 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Plugin/PluginSelector/AdvancedPluginSelectorBase.php(76): Drupal\Core\Cache\CacheableMetadata->applyTo()
#1 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/modules/contrib/plugin/src/Plugin/Field/FieldWidget/PluginSelector.php(60): Drupal\plugin\Plugin\Plugin\PluginSelector\AdvancedPluginSelectorBase->buildSelectorForm()
#2 [internal function]: Drupal\plugin\Plugin\Field\FieldWidget\PluginSelector::processFormElement()
#3 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1009): call_user_func_array()
#4 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#5 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#6 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#7 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#8 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#9 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#10 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(1072): Drupal\Core\Form\FormBuilder->doBuildForm()
#11 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(445): Drupal\Core\Form\FormBuilder->doBuildForm()
#12 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(629): Drupal\Core\Form\FormBuilder->rebuildForm()
#13 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm()
#14 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#15 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#16 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#17 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#19 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#20 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#21 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#22 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#23 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#24 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#25 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#26 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle()
#27 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle()
#28 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#29 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#30 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle()
#31 /home/jenkins/workspace/D9_SANDBOX_LILY_CUSTOM/build/docroot/index.php(19): Drupal\Core\DrupalKernel->handle()
#32 {main}
.
```

**Comment by podarok** [comment]
TODO: to check usage in DIstro - if not used any more - we can deprecate this and remove from distribution, but after community approval
