### ISSUE TITLE
header.html/footer.html in Rose error 500

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2171]
Location | https://sandbox-rose-cus-d9.openy.org/header.html
-- | --
``` 
Error: Cannot use object of type Drupal\Core\Render\Markup as array in openy_rose_preprocess_page() (line 344 of /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/themes/openy_themes/openy_rose/openy_rose.theme)#0 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(287): openy_rose_preprocess_page() #1 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render() #2 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender() #3 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(450): Drupal\Core\Render\Renderer->render() #4 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/sites/default/files/php/twig/5f58ad51c83ba_html--header.html.html.tw_ZC-HRwKl23qQLbdHd0KxZ3WxR/dWblKbomR8fD3K28qmybuWY4GyPM866uBiRP-wMsytk.php(137): Drupal\Core\Template\TwigExtension->escapeFilter() #5 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8db6ab46df60c5d3629ad34b023bfbb6fec754852458808f8655bbf4ced0bad8->doDisplay() #6 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling() #7 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display() #8 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/themes/engines/twig/twig.engine(65): Twig\Template->render() #9 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template() #10 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render() #11 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender() #12 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render() #13 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() #14 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext() #15 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() #16 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/event-dispatcher/LegacyEventDispatcherProxy.php(78): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray() #17 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(163): Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy->dispatch() #18 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #19 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle() #20 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle() #21 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle() #22 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass() #23 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle() #24 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle() #25 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() #26 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() #27 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle() #28 /home/jenkins/workspace/D9_SANDBOX_ROSE_CUSTOM/build/docroot/index.php(19): Drupal\Core\DrupalKernel->handle() #29 {main}.
```

**Comment by sarah-halby** [comment]
Changing to bug because the functionality to available in other themes, but not in Rose.
