### ISSUE TITLE
GroupEx Pro -> PEF: Critical error while changing status of the session

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2388]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Open Y version | 8.x-2.8.0
Open Y installation type | Custom

**Description:**
This issue was identified while trying to change publish status for the newly created node of type session (see more details about publish status here https://github.com/ymcatwincities/openy/issues/2387). 

While saving the node of type session (created during sync from groupex) we got an error: 
```
Error: Call to a member function referencedEntities() on null in Drupal\openy_repeat\RepeatManager->getSessionData() (line 199 of /var/www/docroot/profiles/contrib/openy/modules/custom/openy_repeat/src/RepeatManager.php)
#0 /var/www/docroot/profiles/contrib/openy/modules/custom/openy_repeat/src/RepeatManager.php(526): Drupal\openy_repeat\RepeatManager->getSessionData(Object(Drupal\node\Entity\Node))
#1 /var/www/docroot/profiles/contrib/openy/modules/custom/openy_repeat/modules/openy_repeat_nodes/openy_repeat_nodes.module(30): Drupal\openy_repeat\RepeatManager->recreateSessionInstances(Object(Drupal\node\Entity\Node))
#2 [internal function]: openy_repeat_nodes_entity_update(Object(Drupal\node\Entity\Node))
#3 /var/www/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('openy_repeat_no...', Array)
#4 /var/www/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(201): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_update', Array)
#5 /var/www/docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(800): Drupal\Core\Entity\EntityStorageBase->invokeHook('update', Object(Drupal\node\Entity\Node))
#6 /var/www/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(530): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('update', Object(Drupal\node\Entity\Node))
#7 /var/www/docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(685): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal\node\Entity\Node), true)
#8 /var/www/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(455): Drupal\Core\Entity\ContentEntityStorageBase->doPostSave(Object(Drupal\node\Entity\Node), true)
#9 /var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(801): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\node\Entity\Node))
#10 /var/www/docroot/core/lib/Drupal/Core/Entity/EntityBase.php(339): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object(Drupal\node\Entity\Node))
#11 /var/www/docroot/core/modules/node/src/NodeForm.php(270): Drupal\Core\Entity\EntityBase->save()
#12 [internal function]: Drupal\node\NodeForm->save(Array, Object(Drupal\Core\Form\FormState))
#13 /var/www/docroot/core/lib/Drupal/Core/Form/FormSubmitter.php(113): call_user_func_array(Array, Array)
#14 /var/www/docroot/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState))
#15 /var/www/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(593): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState))
#16 /var/www/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm('node_session_ed...', Array, Object(Drupal\Core\Form\FormState))
#17 /var/www/docroot/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\node\NodeForm), Object(Drupal\Core\Form\FormState))
#18 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#19 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#20 /var/www/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#21 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#22 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#23 /var/www/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#24 /var/www/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#25 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /var/www/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/docroot/profiles/contrib/openy/modules/openy_features/openy_block/modules/openy_block_date/src/StackMiddleware/BlockDateCacheInvalidator.php(52): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/docroot/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#35 {main}
```
![image](https://user-images.githubusercontent.com/6285570/105378495-ee319a80-5c1c-11eb-9bb7-dc835fb289b2.png)

**Steps to reproduce:**
1. Configure GroupEx Pro -> PEF integration 
2. Run drush command `drush openy-pef-gxp-sync` to sync classes and sessions 
3. Go to Content page (/admin/content)
4. Find there newly created session with unpublished status
5. Edit it and mark it as published
6. Try to save.

**Comment by fyaconiello** [comment]
I am also having this issue on my install. Additionally, I encountered this when trying to manually add a location reference as my session imported without a Location being set.

**Comment by podarok** [comment]
Accordingly to the code
```php
      // Program Subcategory reference.
      try {
        if (!$activity->field_activity_category->isEmpty() && $program_subcategory = $activity->field_activity_category->referencedEntities()) {
          $program_subcategory = reset($program_subcategory);

          // Some instances may require unpublished references.
          // Do not skip program subcategory in that case.
          if (!$this->config->get('allow_unpublished_references')) {
            if (!$moderation_wrapper->entity_moderation_status($program_subcategory)) {
              // Skip activity due to unpublished program subcategory.
              continue;
            }
          }

          // Program reference.
          if ($program = $program_subcategory->field_category_program->referencedEntities()) {
            $program = reset($program);

            // Some instances may require unpublished references.
            // Do not skip program in that case.
            if (!$this->config->get('allow_unpublished_references')) {
              if (!$moderation_wrapper->entity_moderation_status($program)) {
                // Skip activity due to unpublished program.
                continue;
              }
            }

            $activity_ids[] = $activity->id();
            $program_subcategory_ids[] = $program_subcategory->id();
            $program_ids[] = $program->id();
          }
        }
      }
```

Line 199  is checking if there are referenced entities and seems like ```field_category_program``` is not an object. Which is weird, right? @ddrozdik 
Why it is not an object? Is this field available? 

In regards to published/unpublished state
```php
          // Some instances may require unpublished references.
          // Do not skip program subcategory in that case.
          if (!$this->config->get('allow_unpublished_references')) {
```
We have an option in config to allow the use of unpublished nodes https://github.com/ymcatwincities/openy/commit/0575c75173333acaac801cf53e1608dac39a1ec0

**Comment by podarok** [comment]
My guess is that there is a confusion how PEF works
We have a requirement of strong bonding between nodes
Program -> Program Subcategory -> Activity -> Class -> Session
Session must reference Class
Class Must reference Activity
Activity Must reference Program Subcategory
Program Subcategory must reference Program

If one of these references is lost - PEF won't work for the whole chain.

**Comment by fyaconiello** [comment]
> If one of these references is lost - PEF won't work for the whole chain.

![image](https://user-images.githubusercontent.com/227515/106000291-aa0b2380-607c-11eb-9f68-b282f6075e7d.png)
I see the sync creating Activity > Class > Session
Activity is associated with the Group Exercise Program Subcategory referenced in the configuration admin
![image](https://user-images.githubusercontent.com/227515/106000494-e048a300-607c-11eb-9920-e491b1ef8fe0.png)

As far as I can tell, my chain is complete, however, session isn't published. And in my case at least, the Location reference on the Session is empty on sync.

![image](https://user-images.githubusercontent.com/227515/106001287-c22f7280-607d-11eb-97c0-33f6c65bfd50.png)

**Comment by podarok** [comment]
@fyaconiello could you also verify you have Program Subcategory and Program in a chain up from Group Excersize node ( 349 )

**Comment by fyaconiello** [comment]
Following the chain identified some maybe strange behavior:

**Session: Gentle Yoga**
![image](https://user-images.githubusercontent.com/227515/106157046-48b48480-6150-11eb-9a9c-fa081eb8967b.png)

**Class: Gentle Yoga**
![image](https://user-images.githubusercontent.com/227515/106157152-67b31680-6150-11eb-8bb4-afca19113ca3.png)

**Activity: Yoga**
![image](https://user-images.githubusercontent.com/227515/106157703-f9228880-6150-11eb-8855-3a73aee05b10.png)

Note: Yoga Activity references another activity in it's Program Subcategory reference field somehow - Is this the issue?

**Activity 2: Group Exercise**
![image](https://user-images.githubusercontent.com/227515/106158158-74843a00-6151-11eb-83aa-7d46e63734d5.png)

**Program Subcategory: Performance Training**
![image](https://user-images.githubusercontent.com/227515/106158333-9e3d6100-6151-11eb-8e8e-74b51339bc82.png)

**Program: Health and Fitness**
![image](https://user-images.githubusercontent.com/227515/106158492-ca58e200-6151-11eb-97c3-a6b3f3006df8.png)

**Comment by fyaconiello** [comment]
confirmed, https://github.com/ymcatwincities/openy/pull/2395.diff patch fixes the issue for me!

**Comment by fyaconiello** [comment]
@podarok I spoke too soon.

the patch above allowed me to save individual sessions from the drupal admin, but when I run the sync command and then execute the cron the issue crops back up:

```
 ~/P/ymca-openy   develop +  terminus drush ymca-ric-openy.develop -- openy-pef-gxp-sync
 [notice] Command: ymca-ric-openy.develop -- drush openy-pef-gxp-sync [Exit: 0]
```

then

```
 ~/P/ymca-openy   develop +  terminus drush ymca-ric-openy.develop -- cron            16.4s  Fri 29 Jan 2021 01:37:19 PM EST
 [notice] Starting execution of captcha_cron().
 [notice] Starting execution of dblog_cron(), execution of captcha_cron() took 0.51ms.
 [notice] Starting execution of field_cron(), execution of dblog_cron() took 12.94ms.
 [notice] Starting execution of file_cron(), execution of field_cron() took 11.6ms.
 [notice] Starting execution of history_cron(), execution of file_cron() took 38.73ms.
 [notice] Starting execution of node_cron(), execution of history_cron() took 0.41ms.
 [notice] Starting execution of scheduler_cron(), execution of node_cron() took 0.01ms.
 [notice] Starting execution of search_api_cron(), execution of scheduler_cron() took 38.98ms.
 [error]  Error: Call to a member function referencedEntities() on null in Drupal\openy_activity_finder\Plugin\search_api\processor\Week->addFieldValues() (line 57 of /code/profiles/contrib/openy/modules/custom/openy_activity_finder/src/Plugin/search_api/processor/Week.php) #0 /code/modules/contrib/search_api/src/Item/Item.php(272): Drupal\openy_activity_finder\Plugin\search_api\processor\Week->addFieldValues(Object(Drupal\search_api\Item\Item))
#1 /code/modules/contrib/search_api/src/Entity/Index.php(975): Drupal\search_api\Item\Item->getFields()
#2 /code/modules/contrib/search_api/src/Entity/Index.php(930): Drupal\search_api\Entity\Index->indexSpecificItems(Array)
#3 /code/modules/contrib/search_api/search_api.module(119): Drupal\search_api\Entity\Index->indexItems(50)
#4 [internal function]: search_api_cron()
#5 /code/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('search_api_cron', Array)
#6 /code/core/lib/Drupal/Core/Cron.php(236): Drupal\Core\Extension\ModuleHandler->invoke('search_api', 'cron')
#7 /code/core/lib/Drupal/Core/Cron.php(134): Drupal\Core\Cron->invokeCronHandlers()
#8 /code/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#9 /opt/pantheon/drush/src/Drupal/Commands/core/DrupalCommands.php(59): Drupal\Core\ProxyClass\Cron->run()
#10 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#11 /opt/pantheon/drush/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#12 /opt/pantheon/drush/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /opt/pantheon/drush/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /opt/pantheon/drush/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /code/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /code/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /code/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /code/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /opt/pantheon/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /opt/pantheon/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /opt/pantheon/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#22 /opt/pantheon/drush/drush-dist(4): require('/opt/pantheon/d...')
#23 {main}. 
 [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.
 [notice] Command: ymca-ric-openy.develop -- drush cron [Exit: 1]
 [error]   
``` 

this has a slightly different stack trace than the original, but im pretty sure its the same root cause.

**Comment by sarah-halby** [comment]
@podarok reopening for you to address when you return on Monday.

**Comment by podarok** [comment]
@fyaconiello try this patch 
https://github.com/ymcatwincities/openy_activity_finder/pull/32/files
And let me know if helped.

In my guts, I feel this is an issue with data setup in Groupex, but with this patch, you should get the code run till the end of the loop.

**Comment by podarok** [comment]
This was fixed and confirmed by Francis
